### ISSUE TITLE
Project Versioning 

### ISSUE THREAD

**Issue by yod527** [olegabu/fabric-starter#27]
Hello.
Could you please add some king of tags or versioning system to be able to add fabric-starter as dependency on other projects?
Thank you.

**Comment by LeonidLe** [comment]
This project does not have release cycle and special regression tests so we probably can't just provide some particular tag like _stable_ or _release_. Perhaps we will have a CI process configured later.

But you can always make a fork and provide tags for your purposes. If you find a state is quite stable we can add your tag in our repository.

You could also just use a commit's SHA which works exactly like a tag in terms of referencing a repository's particular state. 
-Regards-

**Comment by LeonidLe** [comment]
decided to use relatively stable snapshot-x.x branches. See README.md
