### ISSUE TITLE
 peer-listener - Error: Connect Failed on changing the db from default leveldb to CouchDb

### ISSUE THREAD

**Issue by sivachaitanya** [olegabu/fabric-starter#6]
I have got the network to work properly with leveldb configuration, however when I changed the dockercomposetemplate-peer yaml file to include couchdb isntances, I was able to run the couchdb setup and notices there are no errors, however the api(fabric-rest) is exiting saying Failed to connect, can you please help how can I debug this issue ? Following is the log after we do helper.newEventHub(peer, _username, orgID) and the object that is getting returned as - 

[2018-06-06 05:22:54.618] [DEBUG] peer-listener - Connected Event hub data ----EventHub {
  _chaincodeRegistrants: {},
  _block_registrant_count: 1,
  _blockOnEvents: {},
  _blockOnErrors: {},
  _transactionOnEvents: {},
  _transactionOnErrors: {},
  _ep:
   Remote {
     _options:
      { 'grpc.ssl_target_name_override': 'peer0.a.example.com',
        'grpc.default_authority': 'peer0.a.example.com' },
     _url: 'grpcs://peer0.a.example.com:7053',
     _endpoint:
      Endpoint {
        addr: 'peer0.a.example.com:7053',
        creds: ChannelCredentials {} },
     _request_timeout: 45000 },
  _event_client: null,
  _stream: null,
  _connect_called: false,
  _connected: false,
  _connect_running: false,
  _force_reconnect: true,
  _current_stream: 0,
  _clientContext:
   Client {
     _cryptoSuite:
      CryptoSuite_ECDSA_AES {
        _hashAlgo: 'SHA2',
        _keySize: 256,
        _cryptoKeyStore: [Object],
        _curveName: 'secp256r1',
        _ecdsaCurve: [Object],
        _hashFunction: [Function],
        _hashFunctionKeyDerivation: [Object],
        _hashOutputSize: 32,
        _ecdsa: [Object] },
     _channels: {},
     _stateStore: FileKeyValueStore { _dir: '.storage/fabric-client-kvs/peeraAdmin_a' },
     _userContext:
      User {
        _name: 'peeraAdmin',
        _roles: null,
        _affiliation: '',
        _enrollmentSecret: '',
        _identity: [Object],
        _signingIdentity: [Object],
        _mspId: 'aMSP',
        _cryptoSuite: [Object] },
     _msps: Map {},
     _devMode: false } }

**Comment by LeonidLe** [comment]
try Couchdb deployment with new scripts
