### ISSUE TITLE
PEER0 failed to join the channel

### ISSUE THREAD

**Issue by Prskriti** [olegabu/fabric-starter#66]
While running command ./byfn.sh -m up -s couchdb -a each time I am getting Error getting endorser client channel: endorser client failed to connect to peer0.org1.example.com:7051: failed to create new connection: context deadline exceeded.
Can anyone help me in resolving this issue please.I have tried many times.Each and every time I am getting same error.

![Screen Shot 2019-05-06 at 12 39 40 PM](https://user-images.githubusercontent.com/26160349/57210702-3cdb7300-6ffb-11e9-9262-4f708b30c57c.png)

**Comment by LeonidLe** [comment]
Not related to this project
but try to remove old containers with docker rm -f $(docker ps -aq)
