### ISSUE TITLE
Error while removing network

### ISSUE THREAD

**Issue by Prskriti** [olegabu/fabric-starter#67]
Getting ERROR: error while removing network: network net_byfn id 3ba1a87d7b1c419efd047a2a841fe963014d9f1f59b4b7c894920c0fd6ec8cdf has active endpoints while running ./byfn.sh -m down command.
![Screen Shot 2019-05-06 at 1 18 55 PM](https://user-images.githubusercontent.com/26160349/57212269-cfcadc00-7000-11e9-94d2-cd6513678fca.png)

**Comment by LeonidLe** [comment]
Not related to this project but to Hyperledger Fabric's samples
