### ISSUE TITLE
Not clear if REST API Port 4000, 4001, 4002 are exposed with Fabric 1.1

### ISSUE THREAD

**Issue by chainThree** [olegabu/fabric-starter#8]
Hello, excellent resource to get Fabric up and running. 

I am able to stand up all nodes and chaincode is deployed however I am unable to access the admin ports on the peers. I get the Nginx welcome with localhost::80 but localhost:4000/admin fails. Is there an extra step I have to take to expose these ports? Do I have to expose them from Docker to my host or is did something change in Fabric 1.1?

org1 http://localhost:4000/admin
org2 http://localhost:4001/admin
org3 http://localhost:4002/admin

docker inspect api.a.example.com returns Port 4000 for API api.a.example.com

  "NetworkMode": "dockercompose_default",
            "PortBindings": {
                "4000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "4000"
                    }
                ]
Any thoughts?

**Comment by LeonidLe** [comment]
see README for new instructions
